#----------------------------------------------------------------------
# This file was generated by demoIcon.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

Problem = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAABhRJ"
    "REFUWIWtl12IXVcVx39rn3PuvZmZeA01Q5pSWuiLlMQaFLWk9qlRrF9YNFqjVh8sVdBIUWgR"
    "xDxIhSixUCM+WAkFP6AUlIqBYqFUaY2daIiIIFI0H4IiMjN37jlnf6zlwz73ZCYZQqfMhs2B"
    "e9fa+7f+a5219xEzY7vGysrKrfPz8zcURbH0Wn3ctu0OjMfjV0+cOPHwVnxkuxQQEQMwM9mK"
    "37YocOHChcdez+YAZU9y09vf9noB7PLSIx//wqNHt7KGXnplqQc4eurcc3O3fPKet95+E25Q"
    "UVYDXFniigIpHOIEEEwVU0VjQlMkhsCLJ+8D4P7Dhx8/cv8ncCIIYICakZISUyLERPARHyKv"
    "XvoPgGxQ4I59N/PNB+9EnLsyRRARkE5ZMwzDNE/fNrzvJFz89/8oZvbrlcEwA1XDTElqqCo/"
    "O32mt7mSguGIOoIrBGeCQxAn5CVnAGCWlVA17n3XrRRFQdGBOukCm0nQDREjl0cGmt8x6v/r"
    "i7AYjWgStAlaE7wJAUfE8Z79N5AQIo6A4HG0mv3++a//dpt3EE5Y3LWT7x7/Nm7d7yJXApmf"
    "G16rQDEa0apQFo4Sh4mjENfLr+JyXjESyuGDt+QInOCcw7nZRrOo8+9mhuEAxSmoCPM7NgEo"
    "R0Nac51UDsHhxKHdiuYKzAxVQwWCbzn3l7/lKJ30AK4DcJLhTMHEMBHEOVBjbjTYBGA4IJpQ"
    "4ChFsFn0zvHsX9f6IgQj+ADA7t2LiJNeauccAkymbRc5KIrhMNMMJcKOTQEGFdGEUiTL7Rw4"
    "h5Ru/UsAKMcf/lQnP70CRZ8G+lybgeAwFNUrKRpW5SYAVUE0IZmgSLd6fh27NoApYLD0wmn2"
    "7X8LwvrouzkrNjMUwxwUJqgTRDPYYDOAoiyIBomsgIpgLjeh3BNyAdJV/4+f+mlf3dJv7nAu"
    "K2CA0655dZFnNKEo3LUAIkJQMoSBGrkGutwCiMuLAey5cW/nlxfNaoCTDGsmJFGcCKmzQXJz"
    "KmY5XQ9gQJuMQYKQoDIhKt0rmW3UhNQ1mNXJBF8VDMqCsiwoC8d45xvoqcw6JYwNjWz2/9UA"
    "SY02GFU0qmSUySiS4aJ1ThlsZWUVgNtvu5mrhw8RsFwrWLdjbsOqinZP1l0BeoAYlalPFFWi"
    "KAqkUBBBTai64onJsGqOJ/6wxrQOTGrP6tTzwlPf4ewz30Mt18gs7qTWbWokM1LKh1PaDKDx"
    "iUkTu9PPYZLl9hWUMUuQkuFDovaJaZuYNHn+8RdPdIDat14zy6dhVGJSYvcMUUlJe4C+HJs2"
    "sDrNc2UaePTuMV955wLnz/yW5bWYZx1YqSOrdbZZrbO9pcjCwkI+cqP2z4ce/DzjnXM88Okj"
    "hJiPYh8jIaZrFainnpVhiSEkM774zGVO3reXHzx0qDd+890f5q7PfoPhG29k2gTWpoHJWgvA"
    "offey8sv/56vP/I1zi690vvsXlzk+z98ktZH2hD752yImXH01Lnnnj+/cs/CeI6FhRHzcwN2"
    "jCpGg5KydFz60/P8+rHPbCie643di4s8e/o37Nmzl6jaRa80PjBtPKtrDR949/6NF5J6UgN0"
    "eVaaNjIclFRlwcJtB/nYj/6OJiOmROsTdROoa089aTh//C7ecedBTv3kaQqXzxAzY9p6YjJC"
    "TPgQqdvAtG6ZNn6TIpysYRhJlRgjrR8yrArKqsB1R5yqEaPmXDaedtrSTBsAzrz0O6ZN6G17"
    "+5TwIdGGSNN41hrPtGmvBWgnU0wNDYnoI4OhpxlUFOVGgBQTKUR8Gwh1S1s3zK5Ak2mTu2Z3"
    "I0qaK9+HSOsDTZtTUNebKNBO1tCUSCEQWk8YDiiqEle4vhWbGSklko9EHwhtS2xaduz7HPWf"
    "n2R5UmdYEVC7okBM+JAB6iZQt5sAxLUJGiMpBMrWE6oq34yvUsCSkmLIEMGTmhZ27gPgHxcv"
    "smvXm/pOrJ0CIcScBu9pfWDahI0Ajz9wx6HLZ3/1QWiuX97XGU+/xC+/dOT9fPTL3/rQa/P4"
    "CL2s2zGPHTv287zc1vy2DaD7xrQDBw58dSs+2/ZxCrC8vDwej8fLW/H5P9zPV+7UopviAAAA"
    "AElFTkSuQmCC")
getProblemData = Problem.GetData
getProblemImage = Problem.GetImage
getProblemBitmap = Problem.GetBitmap
getProblemIcon = Problem.GetIcon

